### ISSUE TITLE
[Question] Contributing for the Jagex Launcher (RuneScape/OSRS)

### ISSUE THREAD

**Issue by USA-RedDragon** [Open-Wine-Components/ULWGL-protonfixes#10]
Hello,

I maintain a Flatpak for the Jagex Launcher (https://github.com/USA-RedDragon/jagex-launcher-flatpak) that uses GE's Wine-GE-Custom releases. Last night's update to 8-26 pointed me to this project and I'm trying to figure out how that usecase might fit here.

The launcher itself and the RuneScape and official OSRS clients are Windows-native and downloaded + managed through this launcher. There are also 2 third-party clients for OSRS called RuneLite and HDOS that are launched (but not installed, these must be installed separately) via the Jagex Launcher, but these are Java-based, so we just use the Linux-native versions in the Flatpak.

In particular, RuneScape 3 has a couple of fixes that need to be applied for avoiding skybox flickering in and out in some areas and to avoid the game world visually unloading on High/Ultra graphics settings.

RuneScape 3 is also available via Steam and likely is the same game client, so it looks like I can add the fixes to Steam, but this raises questions about applying those fixes to RS3 via the Jagex Launcher

A few questions:

- Does Jagex having it's own launcher mean that we should treat it like a "store" a-la Battle.net?
- To my understanding the Jagex Launcher doesn't really have app IDs like some of the other stores do, does this mean we should define our own for the two Windows-based clients?

Thanks for the project! Looking forward to seeing this succeed!

**Comment by GloriousEggroll** [comment]
It would fall into the same category as many other linux-native and/or flatpak available standalone launchers for specific games. Basically it's no different than Lutris or Heroic in that it needs to integrate ULWGL as a replacement for launching wine. The ULWGL launcher is ulwgl-run, and a testing flatpak is available:

https://github.com/Open-Wine-Components/ULWGL-launcher/releases/tag/0.1-RC3

**Comment by nmlynch94** [comment]
@USA-RedDragon I don't think this needs a gamefix at this point in time does it? The launcher runs by default using proton, and the launchers you can install out of the box work well with default settings. The flickering you mentioned looks to be fixed by a manual settings change in game, and only affects some hardware. The manual installation of RuneLite and HDOS clients are handled by the flatpak installer and are probably outside the scope of what a gamefix would do.

All of this is assuming that there should only be entries for a game if a fix is actually needed to get it running well in proton. Let me know if that assumption is incorrect, but I don't see any other scripts that are empty. 

On a cursory look, I don't see any other fixes that apply no changes, so you could install ULWGL in the flatpak and launch with gameid=0 for default settings. I've done this locally for mine and got it working, although I have a lot of cleanup to do before I push it up.

**Comment by USA-RedDragon** [comment]
A bit bold to assume I couldn't develop and submit my own fixes upstream...

> The flickering you mentioned looks to be fixed by a manual settings change in game, and only affects some hardware

There are two issues, one I've documented with ambient occlusion, which I believe you're referring to here. The other is a skybox flicker that has not yet been fixed and isn't affected by settings changes. Forgive the crappy quick recording, but this happens in a couple of environments and is particularly what I'm looking to target

https://github.com/Open-Wine-Components/ULWGL-protonfixes/assets/13051767/f449ee9e-6c0d-4509-a06c-10030aea2c4e

**Comment by nmlynch94** [comment]
Ah, ok makes sense. I was indeed referring to the ambient occlusion issue. Then I guess whether or not it needs a specific gamefix submitted to this repo will depend on what that fix is.

**Comment by USA-RedDragon** [comment]
Closing as I no longer have a vested interest in RS3 patches on Wine due to https://github.com/USA-RedDragon/jagex-launcher-flatpak/pull/64
